name: ci

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write       # for OIDC into AWS

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: ci
          POSTGRES_DB: payments_test
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-retries=10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install poetry==1.8.4
      - run: poetry install
      - run: poetry run ruff check src
      - run: poetry run mypy src
      - run: poetry run pytest -q --cov=payments_api --cov-fail-under=80
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:ci@localhost:5432/payments_test

  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
      - run: snyk test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build-image:
    needs: [test]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::777766665555:role/gha-payments-api-deploy
          aws-region: us-west-2
      - uses: aws-actions/amazon-ecr-login@v2
      - name: build + push
        run: |
          IMAGE="999988887777.dkr.ecr.us-west-2.amazonaws.com/payments-api:${GITHUB_SHA}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
